import keyMirror from 'keymirror';

export default keyMirror({
  ENTITY_HISTORY_DATE_SELECTED: null,

  ENTITY_HISTORY_FETCH_START: null,
  ENTITY_HISTORY_FETCH_ERROR: null,
  ENTITY_HISTORY_FETCH_SUCCESS: null,

  RECENT_ENTITY_HISTORY_FETCH_START: null,
  RECENT_ENTITY_HISTORY_FETCH_ERROR: null,
  RECENT_ENTITY_HISTORY_FETCH_SUCCESS: null,

  LOG_OUT: null,
});
